In [1]:
import numpy as np

In [2]:
test = [1, 2, 3]

In [3]:
np.array(test)

array([1, 2, 3])

In [7]:
test_matrix = [1, 2, 3],[4, 5, 6]

In [8]:
test_matrix

([1, 2, 3], [4, 5, 6])

In [9]:
np.array(test_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
test_matrix2 = [[1, 2, 3],[4, 5, 6]]

In [11]:
test_matrix2

[[1, 2, 3], [4, 5, 6]]

In [12]:
np.array(test_matrix2)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.array(0,0,5)

ValueError: only 2 non-keyword arguments accepted

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10)-np.arange(1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
zero_array = np.arange(1,10)-np.arange(1,10)

In [18]:
zero_array/zero_array

C:\Users\bhask\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan, nan, nan, nan, nan])